### ISSUE TITLE
Which version of tensorflow are you using ? 

### ISSUE THREAD

**Issue by ariverasa** [sansastra/Trajectory-Prediction#1]
The version of keras on my machine is 2.0.0， tf =2.4.0,  the lstm, seq running OK!

But, I run the seq_atten model,  when model add AttentionDecoder class, remind me the tensorflow is wrong,
I have tried many tensorflow versions, the error as follow:

(1) when tensorflow' version = 2.0.*, 2.1.*, 2.2.*, 2.3.*, 2.4.*, 
the error is "....\lib\site-packages\keras\backend\tensorflow_backend.py", line 47, in get_uid
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'";

(2) when tensorflow' version = 1.15.*, 1.14.*, 1.13.*, 1.12.* ,  1.11.*
the error is "......\tensorflow\python\keras\engine\sequential.py", line 145, in add
    'Found: ' + str(layer))
TypeError: The added layer must be an instance of class Layer. Found: <attention_decoder.AttentionDecoder object at 0x0000015EC3DED048> "

Last, or, can you please tell me about the version of various dependent libraries in this system?

**Comment by sansastra** [comment]
Thanks for pointing out the errors occuring with attention_decoder.py with different versions of  tensorflow (tf).  With older version of tf and keras (not sure which version I used 2 years ago), it was running fine. Now when I tried to replace import keras.layers... all with tensorflow.keras... in attention_decoder code (because of tf_graph related error), Recurrent layer and InputSec can't be imported. We need to find these libraries. The author of code for attention_decoder.py has fixed some issues and updated in meantime. please check here whether it works: https://github.com/asmekal/keras-monotonic-attention/blob/master/attention_decoder.py
But I think the problem will remain same since even the updated code  imports keras..., not  tensorflow.keras.., so in the current form you might get error related to tf_graph.., and importing tensorflow.keras throws other errors.
As of now, I will comment the attention part from model.py. But if you have time and find solution and please do post it here as well. Otherwise try to use Attention layer from tf..
